cors.allowed.origins: http://localhost:9090
hystrix.threadpool.default.coreSize: 1000
hystrix.threadpool.default.maxQueueSize: 100000
hystrix.threadpool.default.queueSizeRejectionThreshold: 100000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000

logging.level.org.springframework.web: ERROR

server.port: 10010